//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoUtilities.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoUtilities.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AES(Advanced Encryption Standard) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AESFullName {
            get {
                return ResourceManager.GetString("AESFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CryptoUtilities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CipherText {
            get {
                return ResourceManager.GetString("CipherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑↑↑復号化↑↑↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓↓↓暗号化↓↓↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化ベクター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitializationVector {
            get {
                return ResourceManager.GetString("InitializationVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号文が空です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCipherTextEmptyError {
            get {
                return ResourceManager.GetString("MessageCipherTextEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化ベクターの長さが不正です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInitializationVectoLengthError {
            get {
                return ResourceManager.GetString("MessageInitializationVectoLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化ベクターが空です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInitializationVectorEmptyError {
            get {
                return ResourceManager.GetString("MessageInitializationVectorEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーが空です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageKeyEmptyError {
            get {
                return ResourceManager.GetString("MessageKeyEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーの長さが不正です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageKeyLengthError {
            get {
                return ResourceManager.GetString("MessageKeyLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレーンテキストが空です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePlainTextEmptyError {
            get {
                return ResourceManager.GetString("MessagePlainTextEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CBCモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeCBC {
            get {
                return ResourceManager.GetString("ModeCBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECBモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeECB {
            get {
                return ResourceManager.GetString("ModeECB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレーンテキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlainText {
            get {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }
    }
}
